### ISSUE TITLE
Try to create the binary file

### ISSUE THREAD

**Issue by PeggyWang888** [HamadYA/GhostFaceNets#11]
Hi, 

I'm very interested in this project. Thanks for your sharing.

Now I am trying to create the binary file, but somehow when evaluating there are some error. 

I pretty sure it is the binary file cause the problem. If I use the binary file that you provided, it works. But if I change the binary file that was produce by myself, the evaluation result looks weird.

Would you please provided the "train.txt" and "property" file to let me know where is the problem in my file.

Thank you.

**Comment by HamadYA** [comment]
Hi,

I do not have them currently as I deleted all the datasets from my Laptop as I have shortage in disk space; however, I downloaded them directly from:
MS1M-ArcFace (85K ids/5.8M images)
https://drive.google.com/file/d/1SXS4-Am3bsKSK615qbYdbA_FMVh3sAvR/view?usp=sharing

or MS1M-RetinaFace
https://drive.google.com/file/d/1JgmzL9OLTqDAZE86pBgETtSQL4USKTFy/view?usp=sharing

This is the main link
https://github.com/deepinsight/insightface/tree/master/recognition/_datasets_


> Hi,
> 
> I'm very interested in this project. Thanks for your sharing.
> 
> Now I am trying to create the binary file, but somehow when evaluating there are some error.
> 
> I pretty sure it is the binary file cause the problem. If I use the binary file that you provided, it works. But if I change the binary file that was produce by myself, the evaluation result looks weird.
> 
> Would you please provided the "train.txt" and "property" file to let me know where is the problem in my file.
> 
> Thank you.

**Comment by PeggyWang888** [comment]
Thank you so much!
