### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by ghost** [HamadYA/GhostFaceNets#12]
Hi! Thank you for the great work.
May I know how you can run inference on images? I would like to compare between two images.
Also, is there a way to load the evaluation dataset without using a binary file?
Thanks!

**Comment by HamadYA** [comment]
> Hi! Thank you for the great work. May I know how you can run inference on images? I would like to compare between two images. Also, is there a way to load the evaluation dataset without using a binary file? Thanks!

Hi,

Yes, you can use eval_folder.py to perform inference on a folder or images.

I created multiple inference files, I attached them below. Hopefully they will help you.

[eval.zip](https://github.com/HamadYA/GhostFaceNets/files/11592710/eval.zip)

**Comment by ghost** [comment]
Thanks so much!
