### ISSUE TITLE
Did you provide the checkpoint of GhostFaceNetsV2?

### ISSUE THREAD

**Issue by jojowick22** [HamadYA/GhostFaceNets#18]
I only found the checkpoint of GhostFaceNetsV1 in the "release".

**Comment by martinenkoEduard** [comment]
> I only found the checkpoint of GhostFaceNetsV1 in the "release".

Have you managed to find weights for V2?

**Comment by HamadYA** [comment]
The GhostFaceNetsV2 weights will not be available for a period of time due to the lack of computational resources I currently have. However, you can always train it from scratch using the training details in the paper.

**Comment by martinenkoEduard** [comment]
> The GhostFaceNetsV2 weights will not be available for a period of time due to the lack of computational resources I currently have. However, you can always train it from scratch using the training details in the paper.

will  RTX 3080 12gb be enough for training this v2 model?
