### ISSUE TITLE
reproduce results of GhostFaceNetV1-1.3-1 (A) model

### ISSUE THREAD

**Issue by ak4ever87** [HamadYA/GhostFaceNets#2]
Hi sir,
I am trying to reproduce the GhostFaceNetV1-1.3-1 (A) model resullts. 
Can you please provide your training code: parametrs, optimiezer, scheduler etc..
Thanks

**Comment by HamadYA** [comment]
> Hi sir, I am trying to reproduce the GhostFaceNetV1-1.3-1 (A) model resullts. Can you please provide your training code: parametrs, optimiezer, scheduler etc.. Thanks

Hi,

Sorry, I just uploaded evaluation.ipynb

Please follow the Datasets and Data Preparation and then, please download the following weights,
https://github.com/HamadYA/GhostFaceNets/releases/download/v1.2/GhostFaceNet_W1.3_S1_ArcFace.h5

and then,
modify and run evaluation.ipynb

Let me know if it worked.

**Comment by HamadYA** [comment]
> Hi sir, I am trying to reproduce the GhostFaceNetV1-1.3-1 (A) model resullts. Can you please provide your training code: parametrs, optimiezer, scheduler etc.. Thanks

I also uploaded two training files. training_script.ipynb and training_script_with_Bias.ipynb
With Bias means that the last convolution in the recognition head has a bias which we found to provide relatively better results

**Comment by HamadYA** [comment]
> Hi sir, I am trying to reproduce the GhostFaceNetV1-1.3-1 (A) model resullts. Can you please provide your training code: parametrs, optimiezer, scheduler etc.. Thanks

Hi,
Is everything is going well?
Can I close the issue?
