### ISSUE TITLE
What is the best pretrained model?

### ISSUE THREAD

**Issue by martinenkoEduard** [HamadYA/GhostFaceNets#20]

**Comment by HamadYA** [comment]
Hi,

For now, it is GhostFaceNetV1-1.3-1 (A) trained on MS1MV3

https://github.com/HamadYA/GhostFaceNets/releases/download/v1.2/GhostFaceNet_W1.3_S1_ArcFace.h5[GhostFaceNetV1-1.3-1 (A)](https://github.com/HamadYA/GhostFaceNets/releases/download/v1.2/GhostFaceNet_W1.3_S1_ArcFace.h5)	MS1MV3
