### ISSUE TITLE
License on pretrained models

### ISSUE THREAD

**Issue by jayavanth** [HamadYA/GhostFaceNets#23]
What is the license on the pretrained models? Can it be used for commercial use?

**Comment by HamadYA** [comment]
> What is the license on the pretrained models? Can it be used for commercial use?

Since the models are published in IEEE Access journal, all articles are published under either the Creative Commons Attribution License (CC BY) or the Creative Commons Attribution, NonCommercial, No Derivatives License (CCBY-NC-ND).

You may check with them if it is eligible for commercial use.

**Comment by mhThomsen** [comment]
@jayavanth Did you find anything relevant from IEEE? It is hard to understand if the creative commons license covers weights or simply the paper itself.

**Comment by jayavanth** [comment]
@mhThomsen CCBY-NC-ND license on a paper only covers contents of paper. That license on a  repository usually only covers the code. Unless the model is checked-in into the repository which is almost never the case. Normally authors mention what license the data/weights have.

I ended up using CompreFace
