### ISSUE TITLE
Can GhostFaceNets be fine tuned for facial landmark detection?

### ISSUE THREAD

**Issue by m-a-x-c** [HamadYA/GhostFaceNets#26]
I am novice and would appreciate some advice. I have a bunch of faces with custom landmarks (x and y coordinates). I want to fine tune GhostFaceNets to detect these x and y coordinates. My question are:

- Is this possible and will it be difficult?
- Would you recommend that I try doing it with a different model instead of GhostFaceNets?

Any help is deeply appreciated.

**Comment by HamadYA** [comment]
> I am novice and would appreciate some advice. I have a bunch of faces with custom landmarks (x and y coordinates). I want to fine tune GhostFaceNets to detect these x and y coordinates. My question are:
> 
> * Is this possible and will it be difficult?
> * Would you recommend that I try doing it with a different model instead of GhostFaceNets?
> 
> Any help is deeply appreciated.

Hi,
GhostFaceNets is a face recognition model, that is built for recognition, verification, or feature extraction purposes to identify people.

To use it as a face detector, or object detector, you need to change the recognition head to a detection head such as YOLO, or DETR and train it on the corresponding data (e.g., WiderFACE for face detection).

Check this github link:
https://github.com/open-mmlab/mmdetection

**Comment by HamadYA** [comment]
Let me know if you have any other questions

> I am novice and would appreciate some advice. I have a bunch of faces with custom landmarks (x and y coordinates). I want to fine tune GhostFaceNets to detect these x and y coordinates. My question are:
> 
> * Is this possible and will it be difficult?
> * Would you recommend that I try doing it with a different model instead of GhostFaceNets?
> 
> Any help is deeply appreciated.

**Comment by mehraanc** [comment]
Thanks for the information. I will look into MMDetection.
