### ISSUE TITLE
Training the model

### ISSUE THREAD

**Issue by Hazqeel09** [HamadYA/GhostFaceNets#29]
I'm trying to train the PyTorch version model with ms1mv3, I need to confirm if it will be a classification task? and how many classes that are being classified?

**Comment by Hazqeel09** [comment]
right now i have around 93K classes, is it right?

So your team train the model to classify these 93K classes using ArcLoss?

**Comment by HamadYA** [comment]
> I need to confirm if it will be a classification task? and how many classes that are being classified?

Hi,

The number of classes can be obtained using:

DATA_ROOT = 'ms1m-retinaface-t1/'
    with open(os.path.join(DATA_ROOT, 'property'), 'r') as f:
        NUM_CLASS, h, w = [int(i) for i in f.read().split(',')]

Which is = 93431

The training aim, utilizing ArcFace, is to learn a similarity learning mechanism that allows distance metric learning to be solved in the classification task by introducing Angular Margin Loss.

You can check works that already implemented the training paradiam on PyTorch such as:

https://github.com/deepinsight/insightface

https://github.com/deepinsight/insightface

**Comment by Hazqeel09** [comment]
I see, thank you!

**Comment by HamadYA** [comment]
> I see, thank you!

Check this too

https://github.com/fdbtrs/PocketNet

**Comment by Hazqeel09** [comment]
Will add to my list to consider, thanks
