### ISSUE TITLE
Why Ghost bottleneck v1 change the size of channels?

### ISSUE THREAD

**Issue by fanaev** [HamadYA/GhostFaceNets#3]
Hello, from this figure you can see that Ghost bottleneck doesn't change the size of channels.
<img width="578" alt="image" src="https://user-images.githubusercontent.com/81157248/236557832-3cd9b43a-047a-4fdb-83c4-b7702a1746d3.png">
so why in Figure of architecture the Ghost bottleneck v1 change the size of channels from a to b?
<img width="468" alt="image" src="https://user-images.githubusercontent.com/81157248/236558248-f4125ddd-63fa-405d-8d76-67df2122a8b8.png">
<img width="246" alt="image" src="https://user-images.githubusercontent.com/81157248/236558306-1cacae93-1966-412e-82d8-a6dc1334b8c9.png">

**Comment by HamadYA** [comment]
Hello,
Thank you for reaching out to us.

Regarding your question, the decision to increase or keep the number of channels inside the ghost module depends on the convolution operation being performed. To locate this operation within the code, please refer to lines 64-83 and 141-151 of the ghost_model.py file. As you may notice, the out variable is being modified in these lines, and the outs variable is set to [16, 24, 24, 40, 40, 80, 80, 80, 80, 112, 112, 160, 160, 160, 160, 160]. Additionally, line 142 includes the statement "make_divisible(out * width, 4)", which modifies the channels.

For more details, please refer to the image attached below, which demonstrates that the number of channels either remains the same or changes based on the convolution operation within the ghost bottleneck.

I hope this helps. Please let me know if you have any further questions or it is not clear yet.

![stride 2](https://user-images.githubusercontent.com/119171585/236610137-f2a5b98e-ea3a-4133-b5ad-87b254d3118d.png)

**Comment by fanaev** [comment]
Thanks for the detailed answer
