### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by brianlcm** [HamadYA/GhostFaceNets#32]
Hello, first of all I would like to thank you for making the code available and I would also like to congratulate you on your work.

I need to replicate the results of the work. In that case, what was the approximate training time you had to generate all the models?

I'm using an Nvidia RTX 3060 GPU, but I've observed that it's taking a long time to run an epoch.

Thank you very much.

**Comment by HamadYA** [comment]
> f the work. In that case, what was the approximate training time you had to generate all the

Hi,

For training, it took around two week to run 50 epochs of 64 batch size for GhostFaceNetV1-1 and around one week for GhostFaceNetV1-2. 

For GhostFaceNetsV2, it would take two-three weeks for around 40 epochs.

I was using one Nvidia RTX 3080 GPU.

**Comment by brianlcm** [comment]
Hi,

Perfect, thank you very much for your reply and your attention. This information is important to me.

Regards!

**Comment by brianlcm** [comment]
> > f the work. In that case, what was the approximate training time you had to generate all the
> 
> Hi,
> 
> For training, it took around two week to run 50 epochs of 64 batch size for GhostFaceNetV1-1 and around one week for GhostFaceNetV1-2.
> 
> For GhostFaceNetsV2, it would take two-three weeks for around 40 epochs.
> 
> I was using one Nvidia RTX 3080 GPU.

Hi,

Perfect, thank you very much for your reply and your attention. This information is important to me.

Regards!
