### ISSUE TITLE
Face recognition

### ISSUE THREAD

**Issue by forucell** [HamadYA/GhostFaceNets#40]
Hello. Thank you for your work.
I'd like to use the model to implement face recognition.

Let's say I have 1000 collections of images. Each collection represents a person with his/her face photos.
Next, I'd like to input a face photo and based on previous photos I need to recognize the person.

Please let me know how to do it.

Do I need to train model with my own dataset(collection of face photos)?

**Comment by HamadYA** [comment]
> Hello. Thank you for your work. I'd like to use the model to implement face recognition.
> 
> Let's say I have 1000 collections of images. Each collection represents a person with his/her face photos. Next, I'd like to input a face photo and based on previous photos I need to recognize the person.
> 
> Please let me know how to do it.
> 
> Do I need to train model with my own dataset(collection of face photos)?

Hi,

You do not need to train your model on custom dataset unless you want to make your model specific for that dataset. However, common face recognition models are trained on large dataset and then generalize to other dataset and the generalization is done by:

1) Using the face recognition model as a feature extractor
2) Extract the features of the collection of face photos
3) Extract the features of the person of interest photo
4) Perform cosine similarity distance between these features and specify a threshold

I hope it is clear now

**Comment by forucell** [comment]
Thank you for clarification.

However, you missed the question about how to use model in API.

Could you please let me know that.

Thank you.

**Comment by HamadYA** [comment]
> API

Hi,
I hope you are well.

I am not sure how to.

**Comment by HamadYA** [comment]
I am closing the issue for now, if you have further questions please re-open or create a new issue.

> Thank you for clarification.
> 
> However, you missed the question about how to use model in API.
> 
> Could you please let me know that.
> 
> Thank you.
