### ISSUE TITLE
Train Result

### ISSUE THREAD

**Issue by Rhee-site** [HamadYA/GhostFaceNets#41]
First of all, thank you for the good research.

I have a question while learning with my own dataset.
I used ghostnetv1.

Finally, I checked the message below.
>>>> Saving latest basic model to: checkpoints/ghostnetv1_w1.3_s2_basic_model_latest.h5
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

Did I make a mistake?

**Comment by HamadYA** [comment]
> Finally, I checked the message below.
> 
> > > > >

Hi,

I do not think that you have made a mistake as in all my experiments I had the same warning.
