### ISSUE TITLE
Pre-trained model for face recognition

### ISSUE THREAD

**Issue by arad2022** [HamadYA/GhostFaceNets#42]
How we can use the pre-trained model for face recognition?
I have two person from each one 3 images and I want to extract embedding and compare them.
Could you please provide any code example and he best way to compare embeddings?

@HamadYA

**Comment by HamadYA** [comment]
> How we can use the pre-trained model for face recognition? I have two person from each one 3 images and I want to extract embedding and compare them. Could you please provide any code example and he best way to compare embeddings?
> 
> @HamadYA

Hi,

Please refer to this similar issue: https://github.com/leondgarse/Keras_insightface/issues/128

**Comment by kiashann** [comment]
> > How we can use the pre-trained model for face recognition? I have two person from each one 3 images and I want to extract embedding and compare them. Could you please provide any code example and he best way to compare embeddings?
> > @HamadYA
> 
> Hi,
> 
> Please refer to this similar issue: [leondgarse/Keras_insightface#128](https://github.com/leondgarse/Keras_insightface/issues/128)

Thanks for your answer. 
Could you please share checkpoints for GhostFaceNetV2?
I just found weights for GhostFaceNetV1 in the repository.
Which model has the high speed for real-time face recognition with good performance?

**Comment by HamadYA** [comment]
> > > How we can use the pre-trained model for face recognition? I have two person from each one 3 images and I want to extract embedding and compare them. Could you please provide any code example and he best way to compare embeddings?
> > > @HamadYA
> > 
> > 
> > Hi,
> > Please refer to this similar issue: [leondgarse/Keras_insightface#128](https://github.com/leondgarse/Keras_insightface/issues/128)
> 
> Thanks for your answer. Could you please share checkpoints for GhostFaceNetV2? I just found weights for GhostFaceNetV1 in the repository. Which model has the high speed for real-time face recognition with good performance?

Hi,

Unfortunately GhostFaceNetV2 checkpoints are not available.

Models with small width multiplier are the real-time ones with good performance. All results with computational complexity you may find in the paper.
