### ISSUE TITLE
Reproduce the Result of the model.

### ISSUE THREAD

**Issue by LionLion888** [HamadYA/GhostFaceNets#5]
Hello~ 

Thank you for sharing the model code. Now I am tring to reproduce the result of the face recognition. Can you please provide the inference code to run the testing data?

Thanks!

**Comment by HamadYA** [comment]
> Hello~
> 
> Thank you for sharing the model code. Now I am tring to reproduce the result of the face recognition. Can you please provide the inference code to run the testing data?
> 
> Thanks!

Hi,

Please follow the Datasets and Data Preparation and then, please download the following weights,
https://github.com/HamadYA/GhostFaceNets/releases/download/v1.2/GhostFaceNet_W1.3_S1_ArcFace.h5

and then,
modify and run evaluation.ipynb

GhostFaceNetsV2 weights are not available for now; I will provide them soon once I retrain them since I found that they are corrupted somehow.

Let me know if it worked.

**Comment by LionLion888** [comment]
Hi HamadYA,

A good news, I successfully run the evaluation.ipynb file and get a result as follow.
<img src="https://github.com/HamadYA/GhostFaceNets/assets/133086055/ebfb3daa-b70b-40f0-9df8-4dfd5333ffb1" height="500px" width="500px">

After getting the result, I would like to ask two questions:
1. Woundering is there a way to print the predict result out? Such as "img1.png, img4.png, Not the same person."
2. Is there a document about "evals" Function? I think if I want to print out the individual result maybe I need to use such as evals.predict() or something like that.

Thanks for your reply.

**Comment by HamadYA** [comment]
> Hi HamadYA,
> 
> A good news, I successfully run the evaluation.ipynb file and get a result as follow. <img alt="" width="500px" height="500px" src="https://user-images.githubusercontent.com/133086055/237597283-ebfb3daa-b70b-40f0-9df8-4dfd5333ffb1.png">
> 
> After getting the result, I would like to ask two questions:
> 
> 1. Woundering is there a way to print the predict result out? Such as "img1.png, img4.png, Not the same person."
> 2. Is there a document about "evals" Function? I think if I want to print out the individual result maybe I need to use such as evals.predict() or something like that.
> 
> Thanks for your reply.

Perfect!
For (1) and (2) I will get back to you at the end of the day hopefully.

**Comment by HamadYA** [comment]
> Hi HamadYA,
> 
> A good news, I successfully run the evaluation.ipynb file and get a result as follow. <img alt="" width="500px" height="500px" src="https://user-images.githubusercontent.com/133086055/237597283-ebfb3daa-b70b-40f0-9df8-4dfd5333ffb1.png">
> 
> After getting the result, I would like to ask two questions:
> 
> 1. Woundering is there a way to print the predict result out? Such as "img1.png, img4.png, Not the same person."
> 2. Is there a document about "evals" Function? I think if I want to print out the individual result maybe I need to use such as evals.predict() or something like that.
> 
> Thanks for your reply.

Hi,

For (1), I think the below should do the job:
Add the following script just below evals.py line 119 if you are using self.PCA_acc or below line 123 if you are not using self.PCA_acc

```py
# Get the index of incorrectly classified pairs based on the current threshold
            incorrect_idx = np.where((self.test_issame[:dists.shape[0]] == True) & (dists < self.acc_thresh) |
                                    (self.test_issame[:dists.shape[0]] == False) & (dists >= self.acc_thresh))[0]

            # Print the incorrectly classified pairs
            print(f"Incorrectly classified pairs (threshold={self.acc_thresh}):")
            for i in incorrect_idx:
                print(f"Pair {i}: {'same' if self.test_issame[i] else 'different'} pair, distance={dists[i]}")
```

![image](https://github.com/HamadYA/GhostFaceNets/assets/119171585/1ab3b334-e7ad-4374-bea2-3372f71a4b35)


For (2), do you mean a documentation?

**Comment by LionLion888** [comment]
Hi HamadYA,

I added the code as you say, and it works!! Thanks a lot.

(2) I look again the evals.py and found that it have write the function.

Thanks for your reply and the help!! Have a nice day.

**Comment by HamadYA** [comment]
> ook again the evals.py and found that it have write the function.

I am glad that everything is working. I will close this issue and feel free to ask if you have any concerns.
