### ISSUE TITLE
How to fine tune your model with my own dataset?

### ISSUE THREAD

**Issue by hungpn68** [HamadYA/GhostFaceNets#50]
Thank you for great project @HamadYA . I want to fine tune your model weight with my Asian's dataset because I see the data you use is mostly European . How to do it ? Once again , thank you very much

**Comment by hungpn68** [comment]
Oh, i'm found solution and close this issue

**Comment by hung2003oke** [comment]
Oh, i'm found solution and close this issue

**Comment by NIKHILDUGAR** [comment]
please post your solution.
im getting the following errors :
when loading a pretrained model:-
  File "GhostFaceNets/cust_train.py", line 367, in __init_type_by_loss__
    return self.arcface
           ^^^^^^^^^^^^
AttributeError: 'Train' object has no attribute 'arcface'

and when i dont load any model:-

Traceback (most recent call last):                                                                                         
  File "GhostFaceNets/cust_train.py", line 23, in <module>                                      
    basic_model = GhostFaceNets.buildin_models("ghostnetv2", dropout=0, emb_shape=512, output_layer='GDC', bn_momentum=0.9,
 bn_epsilon=1e-5) # , stem_strides=1)                                                                                      
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^                                                                                                          
  File "GhostFaceNets/GhostFaceNets.py", line 63, in buildin_models                      
    xx = keras.models.clone_model(xx)                                                                                      
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                      
  File "/usr/local/lib/python3.11/dist-packages/keras/src/models/cloning.py", line 206, in clone_model                     
    config = serialization_lib.serialize_keras_object(model)                                                               
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                               
  File "/usr/local/lib/python3.11/dist-packages/keras/src/saving/serialization_lib.py", line 244, in serialize_keras_object
    inner_config = _get_class_or_fn_config(obj)                                                                            
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                            
  File "/usr/local/lib/python3.11/dist-packages/keras/src/saving/serialization_lib.py", line 372, in _get_class_or_fn_confi
g                                                                                                                          
    config = obj.get_config()                                                                                              
             ^^^^^^^^^^^^^^^^                                                                                              
  File "/usr/local/lib/python3.11/dist-packages/tf_keras/src/engine/functional.py", line 786, in get_config                
    config = copy.deepcopy(get_network_config(self, config=config))                                                        
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                         
  File "/usr/local/lib/python3.11/dist-packages/tf_keras/src/engine/functional.py", line 1585, in get_network_config       
    node_data = node.serialize(                                                                                            
                ^^^^^^^^^^^^^^^                                                                                            
  File "/usr/local/lib/python3.11/dist-packages/tf_keras/src/engine/node.py", line 224, in serialize                       
    raise TypeError(                                                                                                       
TypeError: Layer tf.nn.convolution was passed non-JSON-serializable arguments. Arguments had types: {'filters': <class 'ker
as.src.backend.tensorflow.core.Variable'>, 'strides': [<class 'int'>, <class 'int'>], 'padding': <class 'str'>, 'data_forma
t': <class 'str'>, 'dilations': (<class 'int'>, <class 'int'>)}. They cannot be serialized out when saving the model. 

and can you share the version of tensorflow /keras you are using? I am on keras 3.4.1  and tensorflow   2.17.0
