### ISSUE TITLE
Working with other dataset (qmul-survface)

### ISSUE THREAD

**Issue by cherrykosasih** [HamadYA/GhostFaceNets#54]
Hi, May I get some guide on how to do training, testing, and evaluation on qmul-survface dataset?
Thank you

**Comment by Amrabdelhamed611** [comment]
@cherrykosasih  hi, here is some useful guides i found  on how to prepare a custom data set and it works with ghost nets make sure that the aligned images saved on your drive has same dimensions as the model input (default 112 )

https://github.com/Talgin/preparing_data
https://github.com/deepinsight/insightface/issues/791
