### ISSUE TITLE
MobileFaceNet

### ISSUE THREAD

**Issue by LeeKyungwook** [HamadYA/GhostFaceNets#6]
Thanks for sharing your great work.

I have a question about result in your paper. In page 10, MobileFaceNet[8] achieved 94.70 in IJB-C 1e-4.

Is there any paper or github about this result?? I can't find it anywhere.

**Comment by HamadYA** [comment]
> Thanks for sharing your great work.
> 
> I have a question about result in your paper. In page 10, MobileFaceNet[8] achieved 94.70 in IJB-C 1e-4.
> 
> Is there any paper or github about this result?? I can't find it anywhere.

Hi,
I hope you are well.

You can find it in: 
https://link.springer.com/article/10.1007/s10462-021-09974-2 
page 18, in Table 10, and as shown in attached
![image](https://github.com/HamadYA/GhostFaceNets/assets/119171585/77aefa81-feac-4fce-924c-e548eb371728)

**Comment by LeeKyungwook** [comment]
Thanks!
