### ISSUE TITLE
How to get the image pairs from the bin file?

### ISSUE THREAD

**Issue by LionLion888** [HamadYA/GhostFaceNets#7]
Hi HamadYA,

Now I am trying to use my own data as testing data, before replace it to my own data. In the "Datasets and Data Preparation" part, Evaluating bin files should include jpeg image data pairs. I'm successfully extracted the folder and get the all jpg images, but I couldn't find the data pairs. In the **"evals.py"**, the issame_list: [ True  True  True ... False False False] is represented as the same person or not, and the bins should be several pairs of images name.

![bin](https://github.com/HamadYA/GhostFaceNets/assets/133086055/39dd7d31-b9cb-4031-a269-36127a75a668)

when I try to print out the "bins" to see the pair, I expected to get such as 

img1, img2 
img3, img4
img7, img8

but I get a numers of gibberish, I am wondering to know how can I get the correct pairs? 

![bin2](https://github.com/HamadYA/GhostFaceNets/assets/133086055/7f63cb31-87b0-46b5-bc8f-2bd3f6472891)

**Comment by HamadYA** [comment]
Hi,

You can check the below

https://github.com/HamadYA/GhostFaceNets/issues/5#issuecomment-1544417993

To add the correctly classified pairs:

correct_idx = np.where((self.test_issame[:dists.shape[0]] == True) & (dists >= self.acc_thresh) |
                       (self.test_issame[:dists.shape[0]] == False) & (dists < self.acc_thresh))[0]
incorrect_idx = np.where((self.test_issame[:dists.shape[0]] == True) & (dists < self.acc_thresh) |
                         (self.test_issame[:dists.shape[0]] == False) & (dists >= self.acc_thresh))[0]

print(f"Correctly classified pairs (threshold={self.acc_thresh}):")
for i in correct_idx:
    print(f"Pair {i}: {'same' if self.test_issame[i] else 'different'} pair, distance={dists[i]}")

print(f"Incorrectly classified pairs (threshold={self.acc_thresh}):")
for i in incorrect_idx:
    print(f"Pair {i}: {'same' if self.test_issame[i] else 'different'} pair, distance={dists[i]}")

**Comment by HamadYA** [comment]
> Hi HamadYA,
> 
> Now I am trying to use my own data as testing data, before replace it to my own data. In the "Datasets and Data Preparation" part, Evaluating bin files should include jpeg image data pairs. I'm successfully extracted the folder and get the all jpg images, but I couldn't find the data pairs. In the **"evals.py"**, the issame_list: [ True True True ... False False False] is represented as the same person or not, and the bins should be several pairs of images name.
> 
> ![bin](https://user-images.githubusercontent.com/133086055/238914321-39dd7d31-b9cb-4031-a269-36127a75a668.png)
> 
> when I try to print out the "bins" to see the pair, I expected to get such as
> 
> img1, img2 img3, img4 img7, img8
> 
> but I get a numers of gibberish, I am wondering to know how can I get the correct pairs?
> 
> ![bin2](https://user-images.githubusercontent.com/133086055/238915525-7f63cb31-87b0-46b5-bc8f-2bd3f6472891.png)

Everything is fine now?

**Comment by LionLion888** [comment]
Hi HamadYA,

With your warm help, I successfully get the prediction result as follow.
![235046](https://github.com/HamadYA/GhostFaceNets/assets/133086055/68ba3ce8-dcc9-4796-a7d7-e0bf9c19e94d)

Thanks again for your help :)

**Comment by HamadYA** [comment]
> Hi HamadYA,
> 
> With your warm help, I successfully get the prediction result as follow. ![235046](https://user-images.githubusercontent.com/133086055/239696877-68ba3ce8-dcc9-4796-a7d7-e0bf9c19e94d.png)
> 
> Thanks again for your help :)

Anytime :)
