### ISSUE TITLE
Model Accuracy

### ISSUE THREAD

**Issue by terrykeng** [HamadYA/GhostFaceNets#8]
Hello Hamad,
I am trying to test out the model but I noticed something about the accuracy of the recognition, the recognition only works when the face is in the same position, same background and same lighting as the face used to populate the database else it would not recognize the face, i was wondering if there could be something else i could do to make that better.

**Comment by HamadYA** [comment]
Hi,

I tested the model on many many datasets, even custom datasets and it performed very well. You can see and check eval_folder.py to get the correct inference, since I think that you have something wrong with the inference. 

> Hello Hamad, I am trying to test out the model but I noticed something about the accuracy of the recognition, the recognition only works when the face is in the same position, same background and same lighting as the face used to populate the database else it would not recognize the face, i was wondering if there could be something else i could do to make that better.

**Comment by HamadYA** [comment]
> Hello Hamad, I am trying to test out the model but I noticed something about the accuracy of the recognition, the recognition only works when the face is in the same position, same background and same lighting as the face used to populate the database else it would not recognize the face, i was wondering if there could be something else i could do to make that better.

Everything is fine now?
