### ISSUE TITLE
Would you consider providing a pytorch version of ghostfacenet？

### ISSUE THREAD

**Issue by FelixZhang7** [HamadYA/GhostFaceNets#9]
I'm following this work, but I'm not familiar with tensorflow

**Comment by HamadYA** [comment]
> I'm following this work, but I'm not familiar with tensorflow

Hi,
I am occupied with a lot of projects and creating a PyTorch version of the project would take some time especially for the training script part. But I would suggest to take the GhostNetv1 and GhostNetv2 backbones from:
https://github.com/huawei-noah/Efficient-AI-Backbones
and do the required modifications that I specified in the paper in details.
